---
title: "Ebola_RandomWalk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(mvtnorm)
library(tidyverse)
library(janitor)
library(rjags)
library(lubridate)
library(cowplot)
```
```{r}
colnames <- names(read_csv("data/Data_ DRC Ebola Outbreak, North Kivu and Ituri - MOH-Total.csv"))
eb <- read_csv("data/Data_ DRC Ebola Outbreak, North Kivu and Ituri - MOH-Total.csv", 
               col_names = colnames, skip = 2) %>% 
  mutate(report_date = mdy(report_date))
```
```{r}
eb %>% 
  ggplot(aes(x = report_date, y = confirmed_cases_change)) +
  geom_point() +
  geom_line()
```

#First run
```{r}
eb_RW <- "
model{

#Data Model
for(t in 1:n){
    y[t] ~ dnorm(x[t], tau_obs)
}

#Process Model
for(t in 2:n){
  x[t] ~ dnorm(x[t-1], tau_add)
}

#Priors
x[1] ~ dnorm(x_ic, tau_ic)
tau_obs ~ dgamma(a_obs, r_obs)
tau_add ~ dgamma(a_add, r_add)
}
"
```

```{r}
y <- eb$confirmed_cases_change + 1

data <- list(y = log(y),
             n = length(y),
             x_ic = log(1000),
             tau_ic = 100,
             a_obs = 1,
             r_obs = 1,
             a_add = 1,
             r_add = 1)
```
```{r}
nchain = 3
init <- list()
for(i in 1:nchain){
  y.samp = sample(y,length(y),replace=TRUE)
  init[[i]] <- list(tau_add = 1/var(diff(log(y.samp))),
                    tau_obs = 5/var(log(y.samp)))
}
```

```{r}
j.model   <- jags.model (file = textConnection(eb_RW),
                         data = data,
                         inits = init,
                         n.chains = 3)
```


```{r, fig.asp = 1.0}
jags.out   <- coda.samples (model = j.model,
                            variable.names = c("tau_add","tau_obs", "x"),
                            n.iter = 10000)
#plot(jags.out)
```




```{r}
#gelman.plot(jags.out)
burnin = 6000
jags.burn <- window(jags.out, start = burnin)
```

```{r}
tdate <- eb %>% 
  distinct(report_date) %>% 
  mutate(nrow = row_number()) %>% 
  mutate(nrow = as.character(nrow))

out <- as.matrix(jags.burn) %>% 
  as_tibble() %>% 
  clean_names() %>% 
  dplyr::select(-c(tau_add, tau_obs)) %>% 
  gather(x_1:x_352, key = "nrow", value = "pred") %>% 
  separate(nrow, c("delete", "nrow")) %>% 
  dplyr::select(-delete) %>% 
  sample_n(5000) %>%
  left_join(tdate) #%>% 



outpred <- out %>%
  group_by(report_date, nrow) %>% 
  summarise(cases_pred = median(pred),
            lwr_quantile = quantile(pred, 0.025),
            upr_quantile = quantile(pred, 0.975))

outvar <- as.matrix(jags.burn) %>% 
  as_tibble() %>% 
  clean_names() %>% 
  dplyr::select(c(tau_add, tau_obs)) 


out_pi <- exp(rnorm(nrow(tdate), out$cases_pred, 1/sqrt(outvar$tau_obs)))

p <- eb %>% 
  ggplot() +
  geom_point(aes(x = report_date, y = confirmed_cases_change), alpha = 0.4) +
  #geom_line(aes(x = report_date, y = confirmed_cases_change)) +
  #geom_bar(aes(x = report_date, y = confirmed_cases_change), stat = "identity") +
  #geom_line(aes(x = report_date, y = confirmed_cases_change)) +
  geom_line(data = outpred, aes(x = report_date, y = exp(cases_pred)), color = "red") +
  geom_ribbon(data = outpred, aes(x = report_date, ymin = exp(lwr_quantile), ymax = exp(upr_quantile)), fill = "red", alpha = 0.6) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, 27) +
  xlab("Date") +
  ylab("Number of Ebola Cases")
```

#Second run: by zone

```{r}
colnames <- names(read_csv("/Users/tinacheng/Dropbox/NEFI/EbolaProject/data/Data_ DRC Ebola Outbreak, North Kivu and Ituri - MOH-By-Health-Zone.csv"))
ebz <- read_csv("/Users/tinacheng/Dropbox/NEFI/EbolaProject/data/Data_ DRC Ebola Outbreak, North Kivu and Ituri - MOH-By-Health-Zone.csv", 
                col_names = colnames, skip = 2) %>% 
  mutate(report_date = ymd(report_date))

ebz0 <- ebz %>%
  mutate(confirmed_cases_change = ifelse(confirmed_cases_change < 0, 0, confirmed_cases_change))

zones <- c("Beni","Butembo", "Kalunguta", "Katwa", "Mabalako", "Mandima")
zones_num <- c(1, 2, 3, 4, 5, 6)

zd <- data.frame(health_zone = zones, zones_num = zones_num)

ebzW <- ebz0 %>% 
  mutate(date_week = week(report_date)) %>% 
  group_by(date_week, health_zone, province) %>% 
  summarise(confirmed_cases_weekly = sum(confirmed_cases_change, na.rm = TRUE)) %>%
  filter(health_zone %in% c("Beni", "Kalunguta", "Katwa", "Butembo", "Mabalako", "Mandima")) %>% 
  left_join(zd) 

w30 <- data.frame(date_week = 30)

ebzWeekly <- ebzW %>% 
  ungroup() %>% 
  dplyr::select(-c(province, health_zone)) %>% 
  spread(key = zones_num, value = confirmed_cases_weekly) %>% 
  bind_rows(w30) %>% 
  arrange(date_week)

ebzWeekly39 <- ebzWeekly %>%
  filter(date_week <= 39)



#head(ebzW)
#unique(ebzW$date_week)
```

```{r}
ebz0 %>% 
  ggplot(aes(x = report_date, y = confirmed_cases_change, color = province)) +
  geom_point() +
  geom_line() +
  facet_wrap(~province)
```
```{r, height = 12, width = 12}
ebz0 %>% 
  filter(health_zone %in% c("Beni", "Kalunguta", "Katwa", "Butembo", "Mabalako", "Mandima")) %>% 
  ggplot(aes(x = report_date, y = confirmed_cases_change)) +
  geom_line(data = eb, aes(x = report_date, y = confirmed_cases_change), color = "red", alpha = 0.4) +
  geom_bar(stat = "identity") +
  facet_wrap(~health_zone) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r, height = 12, width = 12}
ebzW %>% 
  filter(health_zone %in% c("Beni", "Kalunguta", "Katwa", "Butembo", "Mabalako", "Mandima")) %>% 
  ggplot(aes(x = date_week, y = confirmed_cases_weekly2)) +
  geom_vline(xintercept = 39) +
  geom_point() +
  #geom_line(data = eb, aes(x = report_date, y = confirmed_cases_change), color = "red", alpha = 0.4) +
  #geom_bar(stat = "identity") +
  #facet_wrap(~health_zone) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  facet_wrap(~health_zone)
```
```{r}
time = ebzWeekly39$date_week
hzones = c(2:7)
nzones = length(hzones)
y = t(ebzWeekly39[,hzones])
indices.na = which(is.na(y), arr.ind = T)
y[indices.na]<-0
```

```{r, eval = FALSE}
## define adjacency between states slected
adj = matrix(c(0,1,1,1,1,0,    ### state-to-state spatial adjacency (self=0)
               1,0,1,0,0,0,
               1,1,0,0,0,0,
               1,0,0,0,1,1,
               1,0,0,1,0,0,
               0,0,0,1,0,0),nzones,nzones,byrow=TRUE)

```

```{r}
#great circle distance: geographic distance (km) between pop-weighted centroids for health zones
adj <- dist.mat

```


```{r}
SpatialRandomWalk = "
model{

  #### Data Model
  for(t in 1:n){
    for(i in 1:nzones){
      y[i,t] ~ dnorm(x[i,t],tau_obs)
    }
  }

  #### Process Model
  for(t in 2:n){
    for(i in 1:nzones){
      mu[i,t] <- x[i,t-1] + alpha * sum(adj[i,1:nzones]*x[1:nzones,t-1])
    }
    x[1:nzones,t] ~ dmnorm(mu[1:nzones,t],Omega_proc[1:6,1:6])
  }
  
  #### Priors
  for(i in 1:nzones){
    x[i,1] ~ dnorm(x_ic,tau_ic)
  }
  #x[indices.na] ~ dunif(0,1000)

  # for(i in 1:nzones)
  # {
  #   for(j in 1:nzones)
  #   {
  #     Omega_proc[i,j] ~ dgamma(a_proc, b_proc) 
  #   }
  # }
  tau_obs ~ dgamma(a_obs,r_obs)
  Omega_proc ~ dwish(R,K)
  alpha ~ dbeta(1,20)
}
"
```


```{r}
SpatialRandomWalkPois = "
model{

  #### Data Model
  for(t in 1:n){
    for(i in 1:nzones){
      y[i,t] ~ dpois(x[i,t])
    }
  }

  #### Process Model
  for(t in 2:n){
    for(i in 1:nzones){
      mu[i,t] <- x[i,t-1] + alpha * sum(adj[i,1:nzones]*x[1:nzones,t-1])
    }
    log(x[1:nzones,t]) ~ dmnorm(log(mu[1:nzones,t]),Omega_proc[1:6,1:6])
  }
  
  #### Priors
  for(i in 1:nzones){
    log(x[i,1]) ~ dnorm(x_ic,tau_ic)
  }
  #x[indices.na] ~ dunif(0,1000)

  # for(i in 1:nzones)
  # {
  #   for(j in 1:nzones)
  #   {
  #     Omega_proc[i,j] ~ dgamma(a_proc, b_proc) 
  #   }
  # }
  
  Omega_proc ~ dwish(R,K)
  alpha ~ dbeta(1,20)
}
"
```

```{r}
data <- list(y = y,
             nzones = nzones,
             n = length(time),
             #indices.na = indices.na,
             a_obs = 0.001,
             r_obs = 0.001,
             #a_proc = 0.001,
             #b_proc = 0.001,
             R = diag(1,6),
             K = 7,
             x_ic = 0,
             tau_ic = 1000,
             adj = adj)

# nchain = 3
# init <- list()
# for(i in 1:nchain){
#   y.samp = sample(y, length(y), replace = TRUE)
#   init[[i]] <- list(tau_obs = 5/var(diff(log(y.samp)), na.rm = TRUE))
# }


```


```{r}
j.model <- jags.model(file = textConnection(SpatialRandomWalk),
                      data = data)
jags.out1 <- coda.samples(j.model,
                          variable.names = c("alpha", "tau_obs", "x", 'Omega_proc'),
                          n.iter = 10000)

j.model <- jags.model(file = textConnection(SpatialRandomWalk),
                      data = data)
jags.out2 <- coda.samples(j.model,
                          variable.names = c("alpha", "tau_obs", "x"),
                          n.iter = 10000)

j.model <- jags.model(file = textConnection(SpatialRandomWalk),
                      data = data)
jags.out3 <- coda.samples(j.model,
                          variable.names = c("alpha", "tau_obs"),
                          n.iter = 10000)

mhlist <- mcmc.list(list(jags.out1[[1]], jags.out2[[1]], jags.out3[[1]]))

gelman.diag(mhlist)
```
```{r}
plot(jags.out1)
plot(mhlist)

j1burn_v2 <- window(jags.out1, start = 4000)
#plot(j1burn)

out <- as.matrix(j1burn_v2)
head(out)
```

```{r}
out_tibble <- as_tibble(out)

out_tibble2 <- out_tibble %>% 
  clean_names() %>% 
  dplyr::select(x_1_1:x_6_39) %>% 
  gather(time, value) %>% 
  separate(time, c("delete","zones_num", "time")) %>% 
  sample_n(1000) 

out_summary <- out_tibble2 %>% 
  mutate(time = as.numeric(time)) %>% 
  group_by(time, zones_num) %>% 
  summarize(conf_cases = median(value),
            low95 = quantile(value, probs=0.025),
            high95 = quantile(value, probs=0.975)) %>% 
  mutate(zones_num = as.numeric(zones_num))

```

```{r}
p_sprw <- out_summary %>% 
  left_join(zd) %>% 
  ggplot() +
  geom_point(data = ebzW, aes(x = date_week, y = confirmed_cases_weekly)) +
  geom_line(aes(x = time, y = conf_cases, color = health_zone)) +
  geom_ribbon(aes(x = time, ymin = low95, ymax = high95, fill = health_zone), alpha = 0.4) +
  facet_wrap(~health_zone) +
  theme(legend.position = "none") +
  xlab("Week") +
  ylab("Confirmed Cases Weekly")
```

#Forecast

```{r}

```


```{r}
Omega_proc_mean <- matrix(0, nrow = 6, ncol = 6)
for(ii in 1:nrow(out))
{
  omegas = out[ii,1:36]
  omega_mat <- matrix(omegas, nrow = 6, ncol = 6, byrow = F)
  Omega_proc_mean <- Omega_proc_mean + solve(omega_mat)
}

Omega_proc_mean <- Omega_proc_mean / nrow(out)


x_out <- out %>%
  as_tibble() %>% 
  dplyr::select(`x[1,1]`:`x[6,39]`) %>% 
  clean_names() %>% 
  gather(key = param, value = value) %>% 
  separate(param, c("name", "zone", "time")) %>% 
  #mutate(param = paste(name1, name2, sep = "_")) %>% 
  dplyr::select(-c(name)) %>% 
  sample_n(1000) %>% 
  group_by(zone, time) %>% 
  summarise(mean_value = mean(value)) %>% 
  mutate(time = as.numeric(time)) %>% 
  arrange(time) %>% 
  spread(key = time, value = mean_value) 

```

```{r}
##` @param IC    Initial Conditions
##` @param r     Intrinsic growth rate
##` @param Kg    Across-site ('global') mean carrying capacity
##` @param alpha Site random effect
##` @param beta  Slope of precipitation effect on K
##` @param ppt   Precipitation forecast
##` @param Q     Process error (default = 0 for deterministic runs)
##` @param n     Size of Monte Carlo ensemble
forecastN <- function(IC,alpha, tau_obs, Omega_proc, adj, nzones = 6, NT = 13, n=nrow(out)){
  N <- array(NA,c(nzones, NT, n))  ## storage
  mu <- matrix(NA, nrow = nzones, ncol = NT)
  Nprev <- IC           ## initialize
  for(t in 1:NT){
    for(i in 1:nzones)
    {
      mu[i,t] <- Nprev[i] + alpha * sum(adj[i,1:nzones]*Nprev)
    }
    
    N[,t,] <- t(rmvnorm(n, mu[1:nzones,t],Omega_proc[1:6,1:6]))                                  
    Nprev <- rowMeans(N[,t,]) ## update IC
  }
  return(N)
}

IC = colMeans(out[,paste('x[', 1:6, ',39]', sep = '')])
alpha = mean(out[,'alpha'])
tau_obs = mean(out[,'tau_obs'])
Omega_proc = Omega_proc_mean



test = forecastN(IC = IC, alpha = alpha, tau_obs = tau_obs, Omega_proc = Omega_proc_mean, adj = dist.mat, nzones = 6, NT = 13, n=50)
```

zone, time, samples
```{r}
for(i in 1:2){
  beta[i] ~ dnorm(0, 0.001)
}

sigma1 ~ dgamma(1,1)

for(i in 1:n1){
  mu1[i] <- beta[1] + beta[2] * X1[i]
  Y1[i] ~ dnorm(mu1[i], sigma1)
}

sigma2 ~dgamma(1,1)
for(i in 1:n2){
  mu2[i] <- beta[1] + beta[2] * X1[i]
  Y2[i] ~ dnorm(mu2[i], sigma1)
}

```

```{r}
runNo <- rep(seq(40,52,1), 300)

Nt <- test %>% 
  as_tibble() %>%
  mutate(zones_num = row_number()) %>% 
  gather("vector", "value", -zones_num) %>% 
  arrange(zones_num) %>% 
  mutate(time = runNo) %>% 
  group_by(zones_num, time) %>% 
  summarise(conf_cases = median(value),
            low95 = quantile(value, 0.025),
            high95 = quantile(value, 0.975)) %>% 
  mutate(predicted = "yes")
Ntout <- out_summary %>% 
  mutate(predicted = "no") %>% 
  full_join(Nt)

ebP <- ebzW %>%
  mutate(samp = ifelse(date_week <= 39, "in", "out"))

pout <- Ntout %>% 
  left_join(zd) %>% 
  ggplot() +
  geom_point(data = ebP, aes(x = date_week, y = confirmed_cases_weekly, shape = samp)) +
  scale_shape_manual(values = c(1, 4)) +
  geom_line(aes(x = time, y = conf_cases, color = as.factor(health_zone), linetype = predicted)) +
  geom_ribbon(aes(x = time, ymin = low95, ymax = high95, fill = as.factor(health_zone)), alpha = 0.5) +
  facet_wrap(~health_zone, scales = "free") +
  theme(legend.position = "none") +
  xlab("Week") +
  ylab("Ebola Cases (weekly)")
  
```

```{r}
N1 <- N[,,1] %>% 
  as_tibble() %>% 
  rownames_to_column("zone_num")

N2 <- N[,,2] %>% 
  as_tibble() %>% 
  mutate(zone_num = 2)

N3 <- N[,,3] %>% 
  as_tibble() %>% 
  mutate(zone_num = 3)

N4 <- N[,,4] %>% 
  as_tibble() %>% 
  mutate(zone_num = 4)

N5 <- N[,,5] %>% 
  as_tibble() %>% 
  mutate(zone_num = 5)

N6 <- N[,,6] %>% 
  as_tibble() %>% 
  mutate(zone_num = 6)

Ntog <- rbind(N1, N2, N3, N4, N5, N6) #%>% 
  gather(V1:V13, key = "weekV", value = "value")

```

